version: '3.8'

services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      - metrics-net-otel
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "influx", "-execute", "'SHOW DATABASES'"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  grafana:
    image: grafana/grafana:8.5.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - metrics-net-otel
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 512M

networks:
  metrics-net-otel:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
