apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_ADMIN_PASSWORD}
    jsonData:
      httpMode: GET
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true